### ISSUE TITLE
SQL Read-Only Error when Configuring Natlas-Server for First Time

### ISSUE THREAD

**Issue by rosswsnider** [natlas/natlas#100]
When installing natlas (v0.5) and configuring it for first use, running `sudo ./setup-server.sh` and then `./add-admin.py USER` results in a write error to ElasticSearch

> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: ‘INSERT INTO user (email, password_hash, is_admin, results_per_page, preview_length) VALUES (?, ?, ?, ?, ?)’] [parameters: (‘USER’, ‘PBKDF2HASH’, 1, 100, 100)] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by 0xdade** [comment]
The intended mechanism for running natlas is as the natlas system user that gets created during setup. I've updated the setup script to fix a flaw in the user creation as well as chown all the project files to the natlas user. So when you want to add an admin user, `su natlas` so that you can read/write the files.

**Comment by jaredscottwilson** [comment]
I'm getting this same error when adding my scope
python3 add-scope.py --scope myscopefile.txt

sqlite3.OperationalError: attempt to write a readonly database
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO scope_item (target, blacklist) VALUES (?, ?)]

**Comment by 0xdade** [comment]
The most likely culprit for this is that the user you're running the script as doesn't have write permissions to the `metadata.db` file. The `metadata.db` file should be owned by the `natlas` user, so you should be able to write to it by doing one of the following:

1. Add your own user to the natlas group and ensure that the metadata.db file is writable by the natlas group.
2. `sudo su natlas` -> `source venv/bin/activate` -> `python3 add-scope.py --scope myscopefile.txt`
3. `sudo su` -> `source venv/bin/activate` -> `python3 add-scope.py --scope myscopefile.txt`
