### ISSUE TITLE
Set SECRET_KEY with setup-server.sh

### ISSUE THREAD

**Issue by tophertimzen** [natlas/natlas#101]
`setup-server.sh` should take care of setting SECRET_KEY if the user doesn't want to modify the `.env` file.

This flow should be implemented in 2 ways (if the `.env` file does not contain the SECRET_KEY of `you-should-set-a-secret-key`)

1. `setup-server` will set it if it's not already in the current environment when you run the setup script. 
2. If it is in the current environment, setup-server will copy that into the .env file

**Comment by tophertimzen** [comment]
Also, this should promote a `0.5.2` release along with #100

**Comment by 0xdade** [comment]
This won't be making it into 0.5.2 primarily because it's not a bugfix. I might be yoloing the versioning right now, but I'm generally trying to keep the patch version reserved for bugfixes. This will definitely be in v0.6.0 though.

**Comment by tophertimzen** [comment]
Makes sense to not include it into `0.5.2` if you are using patch versions just for bug fixes. This will constrain automating the 0.5.x version without adding a SECRET_KEY which will be introduced in a version relatively soon. I'll probably just cherry-pick this commit into my automation.

**Comment by 0xdade** [comment]
You could add it to the .env programmatically without the setup-server so that you're not cherry picking commits. After setup-server.sh finishes running, `echo "SECRET_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)" >> .env`
