### ISSUE TITLE
Dockerize the deployment of the server and agent 

### ISSUE THREAD

**Issue by tophertimzen** [natlas/natlas#107]
Currently the agent and server work on standalone servers, but we cannot always assume an end user will want to deploy that way. We need to shift to a recommended deployment method that supports docker. This will require 3 docker containers, one for the agent, server and elastic database.

**Comment by jafowler** [comment]
Create a local data location:
`docker create --name es-server -v es-data:/usr/share/elasticsearch/data -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:6.6.0`

Start elastic search docker pointing it at the data location:
`sudo docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -v es-data:/usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch:6.6.0`

**Comment by 0xdade** [comment]
Closed by #190. Thanks @ajacques, @jafowler, and @pryorda for the work on this issue. We're still currently missing documentation about deployment via docker, but that will become another issue as we work out the preferred deployment strategies.
