### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by abhijitsharma1010** [natlas/natlas#1095]
**What are you having trouble with?** I am getting this error "curl: (7) Failed to connect to localhost port 5000: Connection refused"

Please tell us what you're having trouble with.

**What have you already tried?** I have tried to stop the firewalld. 

Please share details with us about whatever things you've already tried. Under the output of "#docker ps" command i see natlas/server status as restarting. And i am getting Connection refused error when i try to curl localhost:5000

**What versions are you using?**

**Natlas Server:** `<FILL ME OUT>`6.2.2

**Natlas Agent:** `<FILL ME OUT>`

**Docker Version:** `<FILL ME OUT>` Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.1

**Elastic Version:** `<FILL ME OUT>` 8.6.2
![Natlas](https://user-images.githubusercontent.com/44794851/230844148-55c0e205-8898-409d-9209-b1d42f967702.png)
![Natlas](https://user-images.githubusercontent.com/44794851/230844195-aaf226df-9494-4dbb-8e8e-c43312dc0bef.png)

**Comment by ajacques** [comment]
If you run `docker logs` on the natlas server container, what does it show? Does it give an error message?
