### ISSUE TITLE
Mechanism to authenticate agents

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#11]
Being able to just accept any input we get from anyone who submits work is great, but there may be situations where we want to control our input to only agents that we have explicitly permitted.

**Comment by 0xdade** [comment]
Users can have many agents. Agents have an authorization token that gets passed with their requests. An agent could possibly also be tied to a specific IP address (but could be updated without invalidating the authorization token).

**Comment by tmaher** [comment]
:)
