### ISSUE TITLE
Ability to add non admin users via CLI script

### ISSUE THREAD

**Issue by tophertimzen** [natlas/natlas#112]
Currently we have tooling to add a new admin with `add-admin.py` but no way to add individual users. We should have tooling to support command line operations for adding a user for server owners who do not want to have to use the web UI. 

I think we can change `add-admin.py` to `add-users.py` and have a flag to differentiate between adding a `user` or an `admin`.

```
./add-users.py --admin <email> # makes an admin
./add-users.py <email>              # makes a normal user
```

**Comment by tophertimzen** [comment]
Not sure which milestone to put this for @0xdade , but the implementation should be fairly simple. I'm happy to help work on it.

**Comment by 0xdade** [comment]
If you want to work on it in the next 10 days then it can make it into v0.6.0, otherwise I've assigned it to 0.7. It should be fairly standalone, and you could probably handle #113 while you're at it.
