### ISSUE TITLE
add-admin email validation

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#113]
The `add-admin.py` script doesn't do any validation that an input is an email address. This should be changed.

**Comment by tophertimzen** [comment]
We should be able to do this easily with the python package `validate_email` https://pypi.python.org/pypi/validate_email

**Comment by 0xdade** [comment]
You could also not require an additional dependency by using the existing wtforms implementation, a la https://stackoverflow.com/questions/32062097/using-flask-wtforms-validators-without-using-a-form

But the problem with this is that we're using CSRF protection so the "form" might never validate unless we have a way to disable it specifically for that use case. It looks like you might also be able to do your own validation with `wtforms.validators.Email` except the docs explicitly call it out as "very primited and should only be used in instances where you later verify by other means." But since that's what we're using in the web forms already (and in reality whenever we are actually using email, it can be validated), it might be better to just stick with that. If you can get it to work, that is.

**Comment by tophertimzen** [comment]
Is there currently no validation of e-mail when a user registers either then? If we want to keep the logic for the code base sync'd with how we do it we should do the same in `add-users / add-admin.py` and `/register`. 

Do you want to open a new issue to validate e-mails in /register if this is the case?

**Comment by 0xdade** [comment]
We use the wtforms email validator when a user registers or is invited. It is a primitive check, but it is fine (for now). Getting perfect email validation is damn near impossible, given what ridiculous things are allowed in an email address. But I do want to stick to using one validation for new users, which means figuring out how to reuse the wtforms validation.

The registration form is  `app.auth.forms.RegistrationForm` and you can see the requirements. The validators are called when you do a form.validate. We can work this out together if you want, otherwise you can do the users change and then I'll figure this out eventually to keep the same validation functions for both mechanisms.
