### ISSUE TITLE
Stop running aquatone/chromium as root

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#123]
This is terrible. Literally terrible. You know why. So stop doing it.

To fix this, we'll need to `sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap` and then have the agent use the NMAP_PRIVILEGED environment variable. Once this is done, nmap can run as a normal user but with elevated privileges, and that means natlas-agent can run as a normal user, so when it calls aquatone it won't be doing it as root.

I guess alternatively I could prepend every aquatone call with su, but that is honestly an even worse idea than the first one. Just do it right, dumb dumb.

Additional: https://secwiki.org/w/Running_nmap_as_an_unprivileged_user

**Comment by droberson** [comment]
Looks like the euid == 0 check in natlas-agent.py can be replaced with a capabilities check for /usr/bin/nmap, and the --privileged flag added to nmap's arguments rather than mucking with the environment:

> >>> import subprocess
> >>> foo = subprocess.check_output(["getcap", "/usr/bin/nmap"]).decode("utf-8")
> >>> foo
> '/usr/bin/nmap = cap_net_bind_service,cap_net_admin,cap_net_raw+eip\n'
> >>> if "cap_net_bind_service" in foo and "cap_net_admin" in foo and "cap_net_raw+eip" in foo:
> ...     print("success")
> ... 
> success

setcap can be added to setup-agent.sh after nmap gets installed.

if this sounds reasonable, i can test a bit more and send a PR.

**Comment by 0xdade** [comment]
This would be great, I just had some trouble getting setcap to work the way I expected it to (though the way I expected it to work may have been wrong). If you get a working setup script that does a setcap, please feel free to make a PR against the v0.6.x branch with the setcap changes and the getcap changes to natlas-agent itself. If you can make it so that it prints the capabilities that it's missing on failure, that would be great.
