### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#166]
We need to write documentation regarding how to contribute back to natlas. Rules about what branch to base your contributions on, what to submit your PR against, what linters to use, etc.

**Comment by valescaf** [comment]
I would like to contribute to this issue.

**Comment by 0xdade** [comment]
Closed in 7938325e38e59defd7e09080bb9049d0efa8656e, will make it to master with 0.6.6 release.
