### ISSUE TITLE
add scope fails when tag is not present

### ISSUE THREAD

**Issue by SkillfulHacking** [natlas/natlas#196]
**Affecting:** 
Server

**Version:** 
main branch

**Describe the bug**
unable to add scope due to missing tags

**To Reproduce**
1. source venv
2. python3 add-scope.py scope.txt --verbose

**Expected behavior**
expect scope to be added to db

**Additional context**
```
python3 add-scope.py --scope scope.txt  --verbose
Traceback (most recent call last):
  File "add-scope.py", line 58, in <module>
    main()
  File "add-scope.py", line 53, in main
    importScope(args.scope, False, args.verbose)
  File "add-scope.py", line 23, in importScope
    fail, exist, success = ScopeItem.importScope(line, blacklist)
  File "/opt/natlas2/natlas-server/app/models.py", line 156, in importScope
    if tags:
UnboundLocalError: local variable 'tags' referenced before assignment
```

**Comment by SkillfulHacking** [comment]
If I add a tag to the scope file it will import to scope, however without a tag I received the above error.

**Comment by 0xdade** [comment]
Thank you for your bug report. It slipped through my testing (and since it's manual testing right now, that's especially prone to happening). Luckily it was an easy fix.
