### ISSUE TITLE
Add request tracing and metrics integration

### ISSUE THREAD

**Issue by ajacques** [natlas/natlas#219]
**Is your feature request related to a problem?**
As a service owner, I don't have any insights into where my Natlas system is slow. Are there too many database calls? Is Elasticsearch too slow? Is my view rendering slow? I want to see an easy to digest that shows me what DB calls I'm making and where time is being spent visually.

**Describe the feature you'd like**
Add OpenCensus or OpenTelemetry integrations to the natlas-server (and natlas-agent?) to report a % of requests to the tracing pipeline.

* All SQLAlchemy calls should be included
* All Elasticsearch calls should be included (Include the query itself?)
* Any other remote service calls should be included

Agent-side:
* The entire scan could be instrumented as a trace (using links to the service-side traces). I believe Prometheus can then link into this to produce time-series metrics on how long scans take.

**Have you considered alternative ways to get this feature**
HTTP access logs have total request processing time, but it's challenging to extract meaningful insights out of this.

**Additional context**
* https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-flask
* https://github.com/opentracing-contrib/nginx-opentracing
* https://opentelemetry.io/
* https://openapm.io/landscape
* https://openapm.io/landscape?collector=opencensus-collector,opencensus-agent,prometheus-server,zipkin-server&visualization=prometheus-server,zipkin-server,sentry-server&storage=prometheus-server&instrumentation-lib=sentry&alerting=prometheus-alerting

**Comment by 0xdade** [comment]
I'd like to see this also get introduced for the agents as well for centrally run deployments (where the admin runs the server and all agents). Then agents can opt in to it, like with sentry. Then, even in deployments where users might want to run their own agents, the admins can still at least collect telemetry on their own running agents, even if users aren't shipping that telemetry back from their agents.
