### ISSUE TITLE
Login Required does not apply to Screenshots and Random

### ISSUE THREAD

**Issue by thesubtlety** [natlas/natlas#228]
As the title says, neither [random](https://github.com/natlas/natlas/blob/main/natlas-server/app/host/routes.py#L198) nor [screenshots](https://github.com/natlas/natlas/blob/main/natlas-server/app/host/routes.py#L198) require authentication even if `Login Required` is checked. Is that by design? If so, the user should be made aware up front, as it caught me off guard. Naiively, `@isAuthenticated` on those routes seemed to fix the issue.

**Comment by 0xdade** [comment]
This change was merged in with #222 yesterday. Thanks so much for bringing it to my attention.
