### ISSUE TITLE
Random has an identifier or brings you to the IP page

### ISSUE THREAD

**Issue by tophertimzen** [natlas/natlas#247]
**Is your feature request related to a problem?**

It is not

**Describe the feature you'd like**

When you search with `/random/` it does not bring you to an IP page, resulting in the inability to go back to a previous result. While I am playing the "click random game" I sometimes see something, but realize only after I hit random once more. I would like to have the random button bring me to a random result page so I can make use of back browsing. 

**Have you considered alternative ways to get this feature**

You can make another button that does random but brings me to a page instead of just `/random/`. I understand we want to be able to hit "F5" instead of physically hitting the button with the mouse, so maybe have the button do an IP page, but on `/random/` you can "f5"

**Additional context**

None

**Comment by 0xdade** [comment]
I think I should be able to add javascript to the page that pushes the permalink for each host into the history so that even though the url will always be `/random/` and the f5 will always work, it'll leave a history trail. I'll experiment with this for the next release.
