### ISSUE TITLE
Incompatible Node version

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#262]
**Affecting:** 
Server

**Version:** 
5fc55c4893812d5f5117eb20aff2a1611f2e070b

**Describe the bug**
The version of node that yarn installs is too old. We need to install a newer version from nodesource instead of relying on the version from yarn.

```
sudo apt update
sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**To Reproduce**
1. Try to install.

**Expected behavior**
Installation should work out of the box. It kinda doesn't right now on the one platform we target...

**Comment by pryorda** [comment]
Is this issue in the docker containers as well?

**Comment by 0xdade** [comment]
Nah, the Dockerfile uses an explicitly versioned node base image for the webpack build.
