### ISSUE TITLE
Documentation of Migrating Nweb Data

### ISSUE THREAD

**Issue by tophertimzen** [natlas/natlas#27]
There exists a case where you will want to migrate data from one nweb server to another. It should be documented how to do that for power users.

**Comment by 0xdade** [comment]
For reference when building this documentation (and probably associated tools)

https://discuss.elastic.co/t/migrating-elasticsearch-indices-to-new-cluster/87910/2

**Comment by 0xdade** [comment]
@tophertimzen  https://github.com/natlas/natlas/wiki/Migrating-Natlas-Data Here you go, a wiki and also a script for doing the elastic snapshots and restores.
