### ISSUE TITLE
Add-user script generates invitation link instead of password

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#276]
**Is your feature request related to a problem?**
Nope

**Describe the feature you'd like**
`./add-user.py` is used to bootstrap the application with it's first admin user. This should spit out a registration link instead of spitting out a generated password. We already have the invitetoken concept, though there is another issue with that - #277

**Have you considered alternative ways to get this feature**
Well we could leave it the way it is but that seems unfavorable

**Comment by pryorda** [comment]
👍
