### ISSUE TITLE
Investigate friendly MAIL_FROM

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#297]
**Affecting:** 
Server

**Version:** 
All / Result of #291 

**Describe the bug**
When moving from DB controlled MAIL settings to .env controlled MAIL settings, it was asked whether or not the MAIL_FROM variable supports friendly naming (e.g. `Natlas <noreply@natlas.io`). Upon investigation, it appears that there might be some issues with this that need debugging. I've only tested with a python debugging smtpd server, though. Reference: https://github.com/natlas/natlas/pull/291#discussion_r443288338

**To Reproduce**
1. Set MAIL_FROM to a string like `"Natlas <noreply@natlas.io"`
2. Send mail
3. Huh? `b'From: =?utf-8?q?Natlas?= <noreply@natlas.io>'`

**Expected behavior**
It should send mail with the friendly display name format.

**Comment by ajacques** [comment]
Have we tested to see what happens when we send an email with this `=?utf-8` encoding scheme? This format appears to be valid: https://ncona.com/2011/06/using-utf-8-characters-on-an-e-mail-subject/

**Comment by 0xdade** [comment]
I didn't have a valid mail server on hand to send from where it'd actually get delivered so I haven't. I (mistakenly?) assumed it was a python encoding issue since python3 has weird random utf-8 things all over the place.

**Comment by 0xdade** [comment]
Going to close this since we've been able to prove out the friendly MAIL_FROM value.
