### ISSUE TITLE
Cleanup agent directory sprawl

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#301]
**Is your feature request related to a problem?**
Yeah so the agent right now has a bunch of directories that get created as part of the Dockerfile and then if you want to persist that data you have to mount each folder as an individual volume. One of them is even called `tmp`. How did this make it past code review? (Hint: I didn't do any code reviews when I wrote this stuff 🤣 ). This is mostly a holdover from prior to going docker-only, when running `./setup-agent.sh` could just create folders wherever it wanted on the host system.

**Describe the feature you'd like**
All persistent data should be mounted relative to a single directory that is separate from the application directory. Directory names should also be more descriptive (I'm lookin at you `tmp`)

I'll look towards @ajacques for guidance on how to make this good.

**Comment by ajacques** [comment]
What are the different folders we use?

**Comment by 0xdade** [comment]
Right now `data` `logs` and `tmp` are all created relative to `/opt/natlas/natlas-agent`.

`data` optionally wouldn't be that important to save context, but there's a config option for `NATLAS_SAVE_FAILS` which saves all associated files if a particular scan fails to upload, which makes debugging easier. Logs probably should be persistent at least to some degree, they use a RotatingFileHandler  which I think already cleans up any logs older than 5 rotations (https://github.com/natlas/natlas/blob/main/natlas-agent/natlas/logging.py#L24)

`tmp` is basically only used to store the natlas-services file in that is referenced by the nmap binary as the list of ports to scan, and should be renamed. It's not a big deal to not persist this folder since it would just be fetched next start anyways.

**Comment by ajacques** [comment]
Put it all in tmp/* in separate subfolders?
```
tmp/
   scans/
     {scan_id}/
   logs/ (12-factor app would suggest this goes to stdout anyway)
   natlas-services
```

tmp/ gets marked as read/writeable
