### ISSUE TITLE
Define cycle periods

### ISSUE THREAD

**Issue by uBadRequest** [natlas/natlas#370]
**Is your feature request related to a problem?**
Yes, after running into some problems I decided to remove everything in scope and test with a small scope. I was seeing it getting scanned multiple times in an hour. Like its expecting something to all of a sudden change.

**Describe the feature you'd like**
Either define scan intervals for a group of targets, or an overall scan interval.

**Have you considered alternative ways to get this feature**
Editing the source code.

**Additional context**
I wish I had taken screenshots.

**Comment by 0xdade** [comment]
Closing as duplicate of #231.
