### ISSUE TITLE
Flask import cli behaves wrongly

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#436]
**Version:**
0.6.11

**Describe the bug**
During some refactoring, an inversion was made which defaults all scope imports to being blacklist. This is due to the following:

https://github.com/natlas/natlas/blob/7ef3647206a8c9572e17733ab76de086d1a83c38/natlas-server/app/cli/scope.py#L17

https://github.com/natlas/natlas/blob/7ef3647206a8c9572e17733ab76de086d1a83c38/natlas-server/app/cli/scope.py#L56

You can see that import_items takes a bool called `scope` but `import_scope` takes a bool called `blacklist` and we just pass it along directly instead of inverting it.

**To Reproduce**

1. `flask scope import /data/somefile`
2. `flask shell`
3. `ScopeItem.query.get(1)` or some other id for your newest imported scope items
4. See that they are inserted as blacklist instead of imported as scope

**Expected behavior**
`flask scope import` should default to importing scope, and the flags should be correctly representative of what they are importing as.

**Comment by 0xdade** [comment]
CLI Tests will be required when we fix this. And it'll probably get fixed sooner rather than later and we'll roll up another 0.6 release after all, between this behavior and the scope export failure.

**Comment by ajacques** [comment]
Did you mention that this didn't get reported to Sentry? Do you know if it tried to send an event?

**Comment by 0xdade** [comment]
Nothing at all is getting reported to sentry from what I can tell, which makes it an unrelated problem. There's no exception in sentry for this, and I can't get it to send exceptions when I put in intentionally wrong search queries that are invalid and trigger an execption, either.

```
root@natlas:~# docker exec -ti natlas_server flask shell
Sentry.io enabled and reporting errors to https://sentry.technowizardry.net
Python 3.8.5 (default, Aug  4 2020, 16:24:08)
[GCC 8.3.0] on linux
App: app [production]
Instance: /opt/natlas/natlas-server/instance
>>> 1/0
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
ZeroDivisionError: division by zero
```
