### ISSUE TITLE
Unable to add tag to a scope from GUI

### ISSUE THREAD

**Issue by uBadRequest** [natlas/natlas#461]
**Version:**
Occured on 6.11 and on the current main release on docker hub: 74de64120773

**Describe the bug**
When trying to add a tag to a scope, tag does not get added and error appears "This field is required."
The post request that gets sent doesn't include the target, only the tag name.

**To Reproduce**

1. Add an address to the scope, from the GUI.
2. Attempt to add a tag to the scope, from the GUI.

**Expected behavior**
The tag to be added.

**Screenshots / Logs**
If applicable, add screenshots or logs to help explain your problem.
![image](https://user-images.githubusercontent.com/47282747/91671560-d33b7e00-eaf5-11ea-9f9b-0ad5727f307d.png)
![image](https://user-images.githubusercontent.com/47282747/91671634-7e4c3780-eaf6-11ea-9e68-0b6fd2769632.png)

**Additional context**

**Comment by 0xdade** [comment]
I can't reproduce this, I'm going to need to know more about your setup. The IP address doesn't get sent because at the moment it's tagging the scope by id, which is in the url.

**Comment by uBadRequest** [comment]
That's weird, it has started working as expected now ... hmm I think i'll just close this
