### ISSUE TITLE
Categorizing Screenshots with EyeBaller

### ISSUE THREAD

**Issue by uBadRequest** [natlas/natlas#462]
**Describe the feature you'd like**
Currently, just scrolling through the screenshots section can be quite boring, especially when there is pages of blank screenshots or ones that just aren't that interesting. The feature i'm suggesting is to use tensorflow to categorize the screenshots, while still allowing the ability to just sort by the latest screenshot.

I've used this project in the past, and it does produce good results using their training model.
https://github.com/BishopFox/eyeballer

I was thinking maybe having a queue that would categorize the screenshots once it reached a certain threshold, unless it would make more sense to just run them all individually. 

**Have you considered alternative ways to get this feature**
Hmm.. not really

**Additional context**
I understand we could use the search feature and just search for "screenshots:*" with additional filters but ehh I think i would need to add more nmap scripts to pull out more context... it would definitely be cool if we could save queries. Also, when i'm feeling like just looking at all the screenshots, I prefer viewing them in a gallery format, which you don't really get in the search view ... not too sure if that's a consensus view or not.

Which reminds me... for scan results that don't have screenshots, but its clear that maybe one could have been taken, would having a button to just request screenshots to be taken from aquatone, rather then a full nmap scan, be a nice feature?

**Comment by 0xdade** [comment]
This sounds related to #252 and #183. EyeBaller is probably not going to be introduced. Tensorflow training on the server seems extremely out of scope. You could import all of the images from natlas into EyeBaller if you want, but we probably won't be introducing the capability natively into the platform.

**Comment by 0xdade** [comment]
I'm going to close this out in favor of the other two existing tickets that are more likely to be implemented.

**Comment by uBadRequest** [comment]
The training wouldn't occur on the server, we would just have the server run the model against images, which actually isn't that intensive to do. My VPS can categorize an image in 1 second.
```
17227776/17225924 [==============================] - 1s 0us/step
No seed set, using seed: 277331
Loaded model from file.
100% (1 of 1) |######################################################################################################################################################################################################################################################################| Elapsed Time: 0:00:01 Time:  0:00:01
[{'filename': '/var/lib/docker/volumes/natlas_ns-data/_data/media/original/00/26/00268de44c013d572731169683bdbade1c44fa27a8cff8d447957b95622202dc.png', 'custom404': 0.037739724, 'login': 0.08426803, 'homepage': 0.00072818995, 'oldlooking': 0.0048567653}]
```

We could also "tag" hashes? Maybe we could have the community contribute hashes of known login panels and group them that way.
For example the Windows IIS Server has a hash of
0542e65c2ba1a1fa5317418684c65b88710b6dcb8a43be72cb0e4a03fe876dea. Searching this hash in Natlas, I found 66 results with this hash.
![image](https://user-images.githubusercontent.com/47282747/92335056-45194780-f061-11ea-9db3-b54f47aae9b6.png)
