### ISSUE TITLE
Creation of docs folder / corresponding docs site

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#47]
Documentation about the project should be served up in a docs folder via github pages. This can double as documentation for users who download the repository and want offline documentation.

**Comment by tophertimzen** [comment]
Documentation should also be put somewhere for what config settings need to modified in `natlas.env`

**Comment by tophertimzen** [comment]
The example `systemd` file defined on the natlas-server README describes a `natlas.env` file. This file is expected to be there with the sample systemd unit as shown with 

```
EnvironmentFile=/opt/natlas/natlas-server/natlas.env
```

However, this file is not documented nor is it setup with `setup-server.sh`. This results in the systemd unit failing to run unless that line is removed, or an env file is placed where it is expected. 

@0xdade can we get some documentation for that file or make it such that it is automatically generated in some way? I automate natlas deployments with puppet so I can just make a template env file once I know what to include in it.

**Comment by 0xdade** [comment]
I'll pull that out of the example systemd file because natlas will do it's own environment load from a `.env` file. I'll also update the README accordingly for what can be set in that file.

**Comment by 0xdade** [comment]
https://github.com/slatedocs/slate

**Comment by 0xdade** [comment]
https://docs.natlas.io
