### ISSUE TITLE
FFUF directory/file search on http server

### ISSUE THREAD

**Issue by uBadRequest** [natlas/natlas#500]
**Describe the feature you'd like**
The option to have the tool FFUF scan http hosts for files/directories.

**Have you considered alternative ways to get this feature**
 I have a NSE script that does this, but its super slow. 

**Additional context**
The nmap scripts that are available for scanning http servers for files, are either very slow or the configuration doesn't support just passing it a simple wordlist, with 500k hosts to scans its just not a viable option.

**Comment by 0xdade** [comment]
This appears to be a duplicate of #204

**Comment by uBadRequest** [comment]
> This appears to be a duplicate of #204

Ahh, yes... no worries, I ended up just adding ffuf myself. Just adding a list of the found files under the nmap results.
