### ISSUE TITLE
sleep effectively limits agents to ~10 threads

### ISSUE THREAD

**Issue by mikeleib** [natlas/natlas#56]
https://github.com/natlas/natlas/blob/11e6c2ffa4fd609a49bc5e462e4b52b6f5251b8a/natlas-agent/natlas-agent.py#L119

**Comment by 0xdade** [comment]
The new agent in 2d004dc1fcb6547d5fabaacca32a6bad312256e5 implements a ThreadScan class which allows for the use of a queue to do scanning and we can get rid of the sleep. Leaving this issue open for now because I haven't changed the default behavior to use the queue yet.  Maybe tomorrow.
