### ISSUE TITLE
Implement proper app logging instead of prints

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#67]
The use of random print statements is pretty bad, we should implement a rotatingfilehandler for logging and make use of logging at various levels. This applies to both the agent and the server.

**Comment by 0xdade** [comment]
I'm going to be working on this soon, I just found this information about logging when gunicorn is involved and it looks to be helpful. https://medium.com/@trstringer/logging-flask-and-gunicorn-the-manageable-way-2e6f0b8beb2f

**Comment by ajacques** [comment]
https://medium.com/@sebright/correlating-traces-and-logs-with-opencensus-ac95d9b14b18
