### ISSUE TITLE
Add screenshot search filter

### ISSUE THREAD

**Issue by fdcarl** [natlas/natlas#78]
A search filter to show only results with screenshots would be awesome

**Comment by 0xdade** [comment]
Related to #72 - once I put all the screenshots into an object that I can reference as "screenshots" then I can easily implement a search filter to only return hosts that have one or more screenshots.

**Comment by 0xdade** [comment]
For now this can be done by searching: `httpheadshot:* OR httpsheadshot:*` and then can compare that with any other qualifiers you want (default search operator is AND, so any additional queries will reduce your findings).

I'll still keep this open until there's an easier search term.

**Comment by 0xdade** [comment]
Turns out I hastily closed this issue and the hack that I used doesn't work for queries that are anything more than simply looking for screenshots.
