### ISSUE TITLE
Improved AgentConfig options

### ISSUE THREAD

**Issue by tophertimzen** [natlas/natlas#86]
An admin should be able to tell a natlas agent to scan all ports with -p- and not use the `natlas-services` file. In some environments where not all ports are yet known, some could be outside the top 1000 or unknown of entirely, performing a scan of everything until an operator can limit their scope would be fantastic.

**Comment by 0xdade** [comment]
I'll implement this at the same time that I implement a script group selector for `--script` so that we move beyond just allowing default script scans.
