### ISSUE TITLE
Use a scanning strategy capable of guaranteeing scope coverage

### ISSUE THREAD

**Issue by rosswsnider** [natlas/natlas#90]

**Comment by 0xdade** [comment]
Adding context - 

Currently, the scanning strategy is to pick a random number between 0 and the max number of hosts in scope. Then we go through each network in scope and determine if the index falls within that network or not. Once we find the right network, we select the IP address that corresponds to the random number picked. There is no guarantee that you'll cover your entire scope space, which makes this very unreliable.

This ask is to create a pseudorandom strategy that is able to guarantee that, as long as the system is running long enough, you will scan your entire scope before re-scanning any hosts.

**Comment by 0xdade** [comment]
Closed in 2c3ba5d544e0263f88d0a9ad5b8cc523941e8771
